"""add resource_extras to resource

Revision ID: 17424e6c63bd
Revises: 5c85554112d3
Create Date: 2026-02-19 13:43:03.774170

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17424e6c63bd'
down_revision: Union[str, None] = '5c85554112d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('resource_extras', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'resource_extras')
    # ### end Alembic commands ###
