"""init

Revision ID: 4859ab29adb2
Revises: 
Create Date: 2026-02-18 16:07:16.332291

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4859ab29adb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawlstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('indicator_count', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawlstate_environment'), 'crawlstate', ['environment'], unique=True)
    op.create_table('indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enable_visualization', sa.Boolean(), nullable=False),
    sa.Column('has_ecospheres_extras', sa.Boolean(), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicator_dataset_id'), 'indicator', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_indicator_environment'), 'indicator', ['environment'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filetype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tabular_api_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tabular_api_status', sa.Integer(), nullable=True),
    sa.Column('tabular_api_ok', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource')
    op.drop_index(op.f('ix_indicator_environment'), table_name='indicator')
    op.drop_index(op.f('ix_indicator_dataset_id'), table_name='indicator')
    op.drop_table('indicator')
    op.drop_index(op.f('ix_crawlstate_environment'), table_name='crawlstate')
    op.drop_table('crawlstate')
    # ### end Alembic commands ###
