"""add filesize to resource

Revision ID: 5c85554112d3
Revises: 9e3b07ef73ce
Create Date: 2026-02-19 13:40:27.744111

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c85554112d3'
down_revision: Union[str, None] = '9e3b07ef73ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('filesize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'filesize')
    # ### end Alembic commands ###
