"""checks on indicator and resource

Revision ID: 9e3b07ef73ce
Revises: e4b0342139f8
Create Date: 2026-02-19 10:44:21.730457

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e3b07ef73ce'
down_revision: Union[str, None] = 'e4b0342139f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('checks', sa.JSON(), nullable=True))
    op.drop_column('indicator', 'extras_errors')
    op.add_column('resource', sa.Column('checks', sa.JSON(), nullable=True))
    op.drop_column('resource', 'tabular_api_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('tabular_api_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'checks')
    op.add_column('indicator', sa.Column('extras_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('indicator', 'checks')
    # ### end Alembic commands ###
