"""add extras_errors to indicator

Revision ID: e4b0342139f8
Revises: 4859ab29adb2
Create Date: 2026-02-19 10:11:13.129648

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b0342139f8'
down_revision: Union[str, None] = '4859ab29adb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('extras_errors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator', 'extras_errors')
    # ### end Alembic commands ###
